### ISSUE TITLE
Comparação de datas falha caso o compareTo responda valor abaixo de -1

### ISSUE THREAD

**Issue by ricardo-comar** [mvallim/java-fluent-validator#40]
Ao comparar LocalDate, caso o resultado do compareTo seja inferior a -1, mesmo sendo um cenário esperado como válido, a validação resulta em cenário inválido.

`LocalDate.now().minusYears(10).compareTo(LocalDate.now())`

**Comment by mvallim** [comment]
Resolved in Release 1.7.1

Thank you!
