### ISSUE TITLE
Sharing thread local data when exception occur

### ISSUE THREAD

**Issue by tentativafc** [mvallim/java-fluent-validator#71]
I detected a problem when the validation process throws an exception. The validation process is not finished and the threadlocal is not clearing the objects in memory.

The partial solution was extends AbstractValidator, catch exception and clean threadlocal.

```java
public abstract class MyAbstractValidator<T> extends AbstractValidator<T> {

    @Override
    public ValidationResult validate(T instance) {
        try {
            return super.validate(instance);
        } catch (Exception exc) {
            ValidationContext.remove();
            throw new RuntimeException(exc);
        }
    }
}
```

**Comment by mvallim** [comment]
Hi @tentativafc,

New release on 1.9.2.

Could you check if everything is ok?

Thanks,
