### ISSUE TITLE
Question: is it possible to validate a hash map

### ISSUE THREAD

**Issue by viebel** [mvallim/java-fluent-validator#79]
Great library!

I was wondering if it was possible to validate a string map.
Let's say that I'd like to represent my data entities as string maps.

Would it be possible to define rules and run validation on string maps?

**Comment by mvallim** [comment]
Hi @viebel,

Yes, it is possible.

In the next release cycle we will be making available another collection of predicates for Map <K, V>.

Thanks for all.

**Comment by viebel** [comment]
Awesome!
Thanks.
